spring:
  application:
    name: ReimbursementRequestAPI
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://35.188.29.161:5432/postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

api:
  config:
    api2-url: ${API2_URL}
